# Generated by Django 3.2 on 2021-05-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('stock', '0002_auto_20210522_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sub_category_1_id',
            field=models.ForeignKey(blank=True, db_column='sub_category_1_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_1', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sub_category_2_id',
            field=models.ForeignKey(blank=True, db_column='sub_category_2_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_2', to='categories.category'),
        ),
    ]
