# Generated by Django 3.2 on 2021-05-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_definitions', '0004_alter_activitydefinition_document_type'),
        ('stock', '0003_auto_20210522_1811'),
        ('stock_activities', '0002_auto_20210522_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactivity',
            name='activity_type_id',
            field=models.ForeignKey(blank=True, db_column='activity_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activity_definitions.activitydefinition'),
        ),
        migrations.AlterField(
            model_name='stockactivity',
            name='stock_code',
            field=models.ForeignKey(blank=True, db_column='stock_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_activities', to='stock.stock'),
        ),
    ]
