# Generated by Django 3.2 on 2021-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_activities', '0005_auto_20210522_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactivity',
            name='activity_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockactivity',
            name='stock_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
