# Generated by Django 3.2.4 on 2021-06-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_activities', '0013_auto_20210605_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactivity',
            name='activity_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
