# Generated by Django 3.2.4 on 2021-06-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_definitions', '0008_alter_activitydefinition_activity_type_id'),
        ('stock_activities', '0014_alter_stockactivity_activity_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactivity',
            name='activity_type_id',
            field=models.ForeignKey(blank=True, db_column='activity_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activity_definitions.activitydefinition'),
        ),
    ]
