# Generated by Django 3.2 on 2021-05-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_statements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('activity_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_given_out', models.BooleanField(blank=True, null=True)),
                ('includes_amount', models.BooleanField(blank=True, null=True)),
                ('amount_name', models.TextField(blank=True, null=True)),
                ('includes_expense', models.BooleanField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('dutch', models.TextField(blank=True, null=True)),
                ('french', models.TextField(blank=True, null=True)),
                ('german', models.TextField(blank=True, null=True)),
                ('greek', models.TextField(blank=True, null=True)),
                ('italian', models.TextField(blank=True, null=True)),
                ('portuguese', models.TextField(blank=True, null=True)),
                ('russian', models.TextField(blank=True, null=True)),
                ('spanish', models.TextField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, db_column='document_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='document_statements.documentstatement')),
            ],
            options={
                'db_table': 'activitydefinitions',
            },
        ),
    ]
