# Generated by Django 3.2.4 on 2021-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_definitions', '0007_alter_activitydefinition_activity_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydefinition',
            name='activity_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
