# Generated by Django 3.2 on 2021-05-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_file', models.TextField(blank=True, null=True)),
                ('stock_code', models.ForeignKey(blank=True, db_column='stock_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='stock.stock')),
            ],
            options={
                'db_table': 'stocklinks',
            },
        ),
    ]
