# Generated by Django 3.2 on 2021-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklink',
            name='stock_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
