# Generated by Django 3.2 on 2021-05-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210522_1811'),
        ('stock_links', '0002_alter_stocklink_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklink',
            name='stock_code',
            field=models.ForeignKey(blank=True, db_column='stock_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='stock.stock'),
        ),
    ]
