# Generated by Django 3.2.3 on 2021-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_links', '0003_alter_stocklink_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklink',
            name='stock_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
