# Generated by Django 3.2.4 on 2021-06-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210605_2158'),
        ('stock_links', '0006_auto_20210605_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklink',
            name='link_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocklink',
            name='stock_code',
            field=models.ForeignKey(blank=True, db_column='stock_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_links', to='stock.stock'),
        ),
    ]
