# Generated by Django 3.2.4 on 2021-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_links', '0008_auto_20210605_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklink',
            name='link_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
