# Generated by Django 3.2 on 2021-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.TextField(blank=True, null=True)),
                ('statement_type', models.TextField(blank=True, null=True)),
                ('includes_heading', models.BooleanField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('dutch', models.TextField(blank=True, null=True)),
                ('french', models.TextField(blank=True, null=True)),
                ('german', models.TextField(blank=True, null=True)),
                ('greek', models.TextField(blank=True, null=True)),
                ('italian', models.TextField(blank=True, null=True)),
                ('portuguese', models.TextField(blank=True, null=True)),
                ('russian', models.TextField(blank=True, null=True)),
                ('spanish', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentstatements',
            },
        ),
    ]
