# Generated by Django 3.2 on 2021-05-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.TextField(blank=True, null=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_parent', models.ForeignKey(blank=True, db_column='category_parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
