# Generated by Django 3.2 on 2021-05-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, db_column='category_parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category'),
        ),
    ]
