# Generated by Django 3.2 on 2021-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
