# Generated by Django 3.2.3 on 2021-05-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_alter_name_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
